### ISSUE TITLE
Story

### ISSUE THREAD

**Issue by JenniBee** [Double-Fine-Game-Club/forum-downtime-funtime-adventure#1]
Since this is going to be a point and click adventure game, the most important thing is the story.  We have the basic outline of the story, thanks to Feddlefew: "you have keep a villain monologuing long enough to escape a deathtrap",

Now we have to decide how we are going to handle it - will it be a serious game or a comedy?  That will help to determine the art style too.

We also have to determine the name and gender of the hero, and the name of the villain, as well as why the villain captured the hero.

We'll of course need dialog from both the hero and the villain once we sort out the tone of the game.  And the dialog puzzles will of course determine your success in keeping the villain monologuing.  So we'll need answers from the hero that don't work on the villain, as well as varying levels of responses of the villain depending on how we want to go about you not keeping on track (do we want to have a one wrong move, and goodbye hero, or do we want to have a gradual decline in the villain's interest.

Also, how do we want to determine failure - by game over, or have an instant redo option?

We'll also need to set up an introduction and an ending (we can do these in dialog or have a sequence.  I'll create an issue of the latter, but it's not necessary).

**Comment by Cheeseness** [comment]
> Also, how do we want to determine failure - by game over, or have an instant redo option?

I like to the idea of doing a "what happened to the world" type summary at the end that maybe explores assorted failure states for their grand plan that are determined by how far through the player has progressed?

Part of me kinda likes the idea that the things that keep the villain occupied are things that give him/her a more defined plan. This could perhaps give an opportunity for some interesting duality, and an ending that allows the villain to be defeated because the player knows their plans so intimately (could be told as a post-escape summary).

**Comment by JenniBee** [comment]
I like that idea.  That way if the player were to escape, we could have one ending - but different ones based on if the player doesn't make it, but the villain has a crazier plan.  It would be easiest to keep the scope simple at first, and just have text intros and outros for this.

I think this idea would probably work best for a broad comedy style.  I'm thinking a pastiche of superheroes, like Middle Manager of Justice - that way we could design a really over-the-top villain and pair him with a hero - maybe one like Batman who is human enough to get hurt if they fail.  I'll put together some character ideas later today, and pop them up in the art style issue (#2).

There were some good ideas that came up on the chatroom earlier this morning, so transcribe the chat log here:

(12:16:34 AM) Feddlefew: Trying to think of some deathtrap ideas.
(12:17:26 AM) Cheeseness: Are we thinking crazy rube goldberg style Monkey 2-ish stuff?
(12:17:38 AM) Feddlefew: Kind of?
(12:17:56 AM) Feddlefew: I mean, like once you thwart one part you have to deal with another.
(12:18:12 AM) Feddlefew: Like the "the pit and the pendulum"
(12:21:18 AM) Feddlefew: So you start out strapped to something with a giant saw/pendulum/Paul Bunion anamatronic with real ax threatening to cut you in half, and after you get out of that the room starts filling with molasses….
(12:21:27 AM) Cheeseness: Yeah, the problem with rube goldberg machines is they they're typically one chain with zero redundancy, whereas we want lots of redundancy so that there's lots of stuff for the player to do
(12:22:19 AM) Cheeseness: Did you spot my suggestion of having the villain's plans be flawed, and the way that you distract them into monologuing is by giving them better ideas (helps you escape, but means they're more likely to succeed if you die)?
(12:22:39 AM) Feddlefew: Yeah.
(12:22:47 AM) Cheeseness: So by the end, you've masterminded this brilliant plot, but if you escape, it gets thwarted because you knew every step
(12:23:09 AM) Feddlefew:  You should also get the option to join them.
(12:23:37 AM) Feddlefew: Like, if you fail to escape but helped them craft the perfect plan.
(12:24:02 AM) Cheeseness: I'm also in love with the idea of a villain's only real skill is being able to say "Let me tell you about my plan..." in a comically menacing way
(12:24:17 AM) Cheeseness: A villain whose only real skill is^
(12:24:31 AM) Feddlefew: The master planner is good at planing and telling people his plans.
(12:24:51 AM) Feddlefew: But terrible at doing anything else?
(12:25:10 AM) Cheeseness: Would you have to deal with henchmans as part of your escape?
(12:25:11 AM) Feddlefew: He can't even capture the hero.
(12:26:39 AM) Feddlefew: He just ambushes them at the laundromat  and rants at them while they're trying to wash their superhero costumes and spy suits.
(12:26:57 AM) Feddlefew: Lol
(12:27:16 AM) Cheeseness: Ha ha ha ha
(12:27:30 AM) Cheeseness: Less opportunities for buzzsaws there though
(12:28:07 AM) Feddlefew: I was thinking a warm-up level.
(12:28:09 AM) Cheeseness: "Oh, I see you've escaped my buzz saw of doom. No matter, you won't get past the pit of sharks in clown costumes mwa ha ha ha ha ha"
(12:28:20 AM) Cheeseness: "Now where was I..."
(12:29:03 AM) Feddlefew: Objective: finish laundry and leave before he blows your secret identity.
(12:29:35 AM) Cheeseness: "Oh yes. After I use the flaming ferris wheel to roll through the feeble military forces surrounding the govenor's mansion, I'll use this paper parachute to drop safely into the main foyer"
(12:30:37 AM) Cheeseness: I have a sweet voice in mind if that sort of silly villain is something that people want to pursue
(12:31:26 AM) Feddlefew: IF we're doing point-and-click, maybe the dialog options should float around the top of the screen?
(12:31:31 AM) Feddlefew: Like thought bubbles.
(12:31:46 AM) Feddlefew: I think we need to have a fronteersman villian.
(12:32:19 AM) Feddlefew: Who tries to kill you with mecha Paul Bunion. 

I like the Frontiersman type villain and the mecha Paul Bunion. :P  I'll draw up concepts for them tomorrow.

**Comment by JenniBee** [comment]
Since the skeleton engine is now up (yay!), to get this project moving forward a bit, I'll close this as the [design documents](https://github.com/Double-Fine-Game-Club/forum-downtime-funtime-adventure/wiki/design-notes) are now up based on our brainstorming.  It looks like we're going to be doing a comedy with a villain named Frontiersman.  That should be fun. :)

I'll open up some issues from some more specific story points so we can start cracking on this.
